#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9 0
#bspc wm --reorder-monitors HDMI-0 DP-4
bspc wm --reorder-monitors DP-4 HDMI-0

bspc config border_width          2
bspc config window_gap            5

# bspc config normal_border_color   '#370a37'
# bspc config focused_border_color  '#e048e0'
# bspc config active_border_color   '#370a37'

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Auto Start
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

#openrazer-daemon -Fv & # Razer stuff
#dunst & # Notifications
#/usr/lib/polkit-kde-authentication-agent-1 & # Password Promt 
lxqt-policykit-agent &
picom -b # Compositor
nitrogen --restore # Wallpapers
imwheel -b 45 # Faster Scrolling
# Disable monitor from turning off automatically
# It's annoying, since half the time it wont turn back on
xset s off -dpms

xset r rate 300 50
xset m 1/1 0

$HOME/.config/polybar/launch.sh # Bar

# Window Rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
